import { ResolvedTheme } from '../types';

export const DEFAULT_THEME: ResolvedTheme = {
  fontFamily: 'system-ui, -apple-system, sans-serif',
  fontSizeTick: '0.75rem',
  fontSizeLabel: '0.875rem',
  fontSizeTitle: '1rem',
  fontWeightNormal: 400,
  fontWeightBold: 700,
  colorBackground: '#ffffff',
  colorSurface: '#ffffff',
  colorText: '#333333',
  colorTextSecondary: '#666666',
  colorBorder: '#cccccc',
  colorTick: '#767676',
  colorError: '#dc3545',
  colorFocusRing: '#0066cc',
  colorLink: '#0563C1',
  borderRadius: '4px',
  gridOpacity: 0.2,
  tooltipPadding: '8px 12px',
  tooltipBoxShadow: '0 2px 4px rgba(0,0,0,0.15)',
  seriesColors: ['#4e79a7', '#e15759', '#76b7b2', '#59a14f', '#edc949', '#af7aa1', '#ff9da7', '#9c755f'],
  mapColors: ['#c6dbef', '#9ecae1', '#6baed6', '#3182bd', '#08519c'],
};

export const CSS_PROPERTY_MAP: Record<keyof Omit<ResolvedTheme, 'seriesColors' | 'mapColors'>, string> = {
  fontFamily: '--jsc-font-family',
  fontSizeTick: '--jsc-font-size-tick',
  fontSizeLabel: '--jsc-font-size-label',
  fontSizeTitle: '--jsc-font-size-title',
  fontWeightNormal: '--jsc-font-weight-normal',
  fontWeightBold: '--jsc-font-weight-bold',
  colorBackground: '--jsc-color-background',
  colorSurface: '--jsc-color-surface',
  colorText: '--jsc-color-text',
  colorTextSecondary: '--jsc-color-text-secondary',
  colorBorder: '--jsc-color-border',
  colorTick: '--jsc-color-tick',
  colorError: '--jsc-color-error',
  colorFocusRing: '--jsc-color-focus-ring',
  colorLink: '--jsc-color-link',
  borderRadius: '--jsc-border-radius',
  gridOpacity: '--jsc-grid-opacity',
  tooltipPadding: '--jsc-tooltip-padding',
  tooltipBoxShadow: '--jsc-tooltip-box-shadow',
};
