import { ResolvedTheme } from '../types';

export const DEFAULT_THEME: ResolvedTheme = {
  fontFamily: 'system-ui, -apple-system, sans-serif',
  fontSizeTick: '0.75rem',
  fontSizeLabel: '0.875rem',
  fontSizeTitle: '1rem',
  letterSpacing: '0',
  fontWeightNormal: 400,
  fontWeightBold: 700,
  colorBackground: '#ffffff',
  colorSurface: '#ffffff',
  colorText: '#333333',
  colorTextSecondary: '#666666',
  colorBorder: '#cccccc',
  colorTick: '#767676',
  colorError: '#dc3545',
  colorFocusRing: '#0066cc',
  colorLink: '#0563C1',
  borderRadius: '4px',
  gridOpacity: 0.2,
  tooltipPadding: '8px 12px',
  tooltipBoxShadow: '0 2px 4px rgba(0,0,0,0.15)',
  burgerMenuBackground: '#ffffff',
  burgerMenuBorderColor: '#bdbdbd',
  burgerMenuBorderRadius: '18px',
  burgerMenuShadow: '0 4px 16px rgba(0, 0, 0, 0.12)',
  burgerMenuItemHoverBackground: '#f5f5f5',
  burgerMenuItemActiveBackground: '#eef5ff',
  burgerMenuItemSeparatorColor: '#e3e3e3',
  seriesColors: ['#1A56EC', '#F2644C', '#1B3160', '#9C8D87', '#26625D', '#7791E8', '#8C1131', '#878EAF', '#C73268', '#288C72'],
  mapColors: ['#c6dbef', '#9ecae1', '#6baed6', '#3182bd', '#08519c'],
};

export const CSS_PROPERTY_MAP: Record<keyof Omit<ResolvedTheme, 'seriesColors' | 'mapColors'>, string> = {
  fontFamily: '--jsc-font-family',
  fontSizeTick: '--jsc-font-size-tick',
  fontSizeLabel: '--jsc-font-size-label',
  fontSizeTitle: '--jsc-font-size-title',
  letterSpacing: '--jsc-letter-spacing',
  fontWeightNormal: '--jsc-font-weight-normal',
  fontWeightBold: '--jsc-font-weight-bold',
  colorBackground: '--jsc-color-background',
  colorSurface: '--jsc-color-surface',
  colorText: '--jsc-color-text',
  colorTextSecondary: '--jsc-color-text-secondary',
  colorBorder: '--jsc-color-border',
  colorTick: '--jsc-color-tick',
  colorError: '--jsc-color-error',
  colorFocusRing: '--jsc-color-focus-ring',
  colorLink: '--jsc-color-link',
  borderRadius: '--jsc-border-radius',
  gridOpacity: '--jsc-grid-opacity',
  tooltipPadding: '--jsc-tooltip-padding',
  tooltipBoxShadow: '--jsc-tooltip-box-shadow',
  burgerMenuBackground: '--jsc-burger-menu-background',
  burgerMenuBorderColor: '--jsc-burger-menu-border-color',
  burgerMenuBorderRadius: '--jsc-burger-menu-border-radius',
  burgerMenuShadow: '--jsc-burger-menu-shadow',
  burgerMenuItemHoverBackground: '--jsc-burger-menu-item-hover-background',
  burgerMenuItemActiveBackground: '--jsc-burger-menu-item-active-background',
  burgerMenuItemSeparatorColor: '--jsc-burger-menu-item-separator-color',
};
