name: Jsonstatgraphs CD (test)

on:
  workflow_call:

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/cd-publish.yml
    with:
      environment: test
      npm-tag: test
      prerelease-env: t
      prerelease: true
      staged-publish: false